;;;; constants.lisp
;;;; DO NOT MODIFY - this file is automatically generated
(in-package #:cl-user)

(defpackage syscall.constants
  (:use #:cl)
  (:export
   #:+SYSCALL+
   #:+EXIT+
   #:+FORK+
   #:+READ+
   #:+WRITE+
   #:+OPEN+
   #:+CLOSE+
   #:+WAIT4+
   #:+LINK+
   #:+UNLINK+
   #:+CHDIR+
   #:+FCHDIR+
   #:+MKNOD+
   #:+CHMOD+
   #:+CHOWN+
   #:+GETFSSTAT+
   #:+GETPID+
   #:+SETUID+
   #:+GETUID+
   #:+GETEUID+
   #:+PTRACE+
   #:+RECVMSG+
   #:+SENDMSG+
   #:+RECVFROM+
   #:+ACCEPT+
   #:+GETPEERNAME+
   #:+GETSOCKNAME+
   #:+ACCESS+
   #:+CHFLAGS+
   #:+FCHFLAGS+
   #:+SYNC+
   #:+KILL+
   #:+GETPPID+
   #:+DUP+
   #:+PIPE+
   #:+GETEGID+
   #:+PROFIL+
   #:+SIGACTION+
   #:+GETGID+
   #:+SIGPROCMASK+
   #:+GETLOGIN+
   #:+SETLOGIN+
   #:+ACCT+
   #:+SIGPENDING+
   #:+SIGALTSTACK+
   #:+IOCTL+
   #:+REBOOT+
   #:+REVOKE+
   #:+SYMLINK+
   #:+READLINK+
   #:+EXECVE+
   #:+UMASK+
   #:+CHROOT+
   #:+MSYNC+
   #:+VFORK+
   #:+MUNMAP+
   #:+MPROTECT+
   #:+MADVISE+
   #:+MINCORE+
   #:+GETGROUPS+
   #:+SETGROUPS+
   #:+GETPGRP+
   #:+SETPGID+
   #:+SETITIMER+
   #:+SWAPON+
   #:+GETITIMER+
   #:+GETDTABLESIZE+
   #:+DUP2+
   #:+FCNTL+
   #:+SELECT+
   #:+FSYNC+
   #:+SETPRIORITY+
   #:+SOCKET+
   #:+CONNECT+
   #:+GETPRIORITY+
   #:+BIND+
   #:+SETSOCKOPT+
   #:+LISTEN+
   #:+SIGSUSPEND+
   #:+GETTIMEOFDAY+
   #:+GETRUSAGE+
   #:+GETSOCKOPT+
   #:+READV+
   #:+WRITEV+
   #:+SETTIMEOFDAY+
   #:+FCHOWN+
   #:+FCHMOD+
   #:+SETREUID+
   #:+SETREGID+
   #:+RENAME+
   #:+FLOCK+
   #:+MKFIFO+
   #:+SENDTO+
   #:+SHUTDOWN+
   #:+SOCKETPAIR+
   #:+MKDIR+
   #:+RMDIR+
   #:+UTIMES+
   #:+FUTIMES+
   #:+ADJTIME+
   #:+GETHOSTUUID+
   #:+SETSID+
   #:+GETPGID+
   #:+SETPRIVEXEC+
   #:+PREAD+
   #:+PWRITE+
   #:+NFSSVC+
   #:+STATFS+
   #:+FSTATFS+
   #:+UNMOUNT+
   #:+GETFH+
   #:+QUOTACTL+
   #:+MOUNT+
   #:+CSOPS+
   #:+WAITID+
   #:+ADD_PROFIL+
   #:+KDEBUG_TRACE+
   #:+SETGID+
   #:+SETEGID+
   #:+SETEUID+
   #:+SIGRETURN+
   #:+CHUD+
   #:+FDATASYNC+
   #:+STAT+
   #:+FSTAT+
   #:+LSTAT+
   #:+PATHCONF+
   #:+FPATHCONF+
   #:+GETRLIMIT+
   #:+SETRLIMIT+
   #:+GETDIRENTRIES+
   #:+MMAP+
   #:+LSEEK+
   #:+TRUNCATE+
   #:+FTRUNCATE+
   #:+__SYSCTL+
   #:+MLOCK+
   #:+MUNLOCK+
   #:+UNDELETE+
   #:+ATSOCKET+
   #:+ATGETMSG+
   #:+ATPUTMSG+
   #:+ATPSNDREQ+
   #:+ATPSNDRSP+
   #:+ATPGETREQ+
   #:+ATPGETRSP+
   #:+MKCOMPLEX+
   #:+STATV+
   #:+LSTATV+
   #:+FSTATV+
   #:+GETATTRLIST+
   #:+SETATTRLIST+
   #:+GETDIRENTRIESATTR+
   #:+EXCHANGEDATA+
   #:+SEARCHFS+
   #:+DELETE+
   #:+COPYFILE+
   #:+FGETATTRLIST+
   #:+FSETATTRLIST+
   #:+POLL+
   #:+WATCHEVENT+
   #:+WAITEVENT+
   #:+MODWATCH+
   #:+GETXATTR+
   #:+FGETXATTR+
   #:+SETXATTR+
   #:+FSETXATTR+
   #:+REMOVEXATTR+
   #:+FREMOVEXATTR+
   #:+LISTXATTR+
   #:+FLISTXATTR+
   #:+FSCTL+
   #:+INITGROUPS+
   #:+POSIX_SPAWN+
   #:+FFSCTL+
   #:+NFSCLNT+
   #:+FHOPEN+
   #:+MINHERIT+
   #:+SEMSYS+
   #:+MSGSYS+
   #:+SHMSYS+
   #:+SEMCTL+
   #:+SEMGET+
   #:+SEMOP+
   #:+MSGCTL+
   #:+MSGGET+
   #:+MSGSND+
   #:+MSGRCV+
   #:+SHMAT+
   #:+SHMCTL+
   #:+SHMDT+
   #:+SHMGET+
   #:+SHM_OPEN+
   #:+SHM_UNLINK+
   #:+SEM_OPEN+
   #:+SEM_CLOSE+
   #:+SEM_UNLINK+
   #:+SEM_WAIT+
   #:+SEM_TRYWAIT+
   #:+SEM_POST+
   #:+SEM_GETVALUE+
   #:+SEM_INIT+
   #:+SEM_DESTROY+
   #:+OPEN_EXTENDED+
   #:+UMASK_EXTENDED+
   #:+STAT_EXTENDED+
   #:+LSTAT_EXTENDED+
   #:+FSTAT_EXTENDED+
   #:+CHMOD_EXTENDED+
   #:+FCHMOD_EXTENDED+
   #:+ACCESS_EXTENDED+
   #:+SETTID+
   #:+GETTID+
   #:+SETSGROUPS+
   #:+GETSGROUPS+
   #:+SETWGROUPS+
   #:+GETWGROUPS+
   #:+MKFIFO_EXTENDED+
   #:+MKDIR_EXTENDED+
   #:+IDENTITYSVC+
   #:+SHARED_REGION_CHECK_NP+
   #:+VM_PRESSURE_MONITOR+
   #:+PSYNCH_RW_LONGRDLOCK+
   #:+PSYNCH_RW_YIELDWRLOCK+
   #:+PSYNCH_RW_DOWNGRADE+
   #:+PSYNCH_RW_UPGRADE+
   #:+PSYNCH_MUTEXWAIT+
   #:+PSYNCH_MUTEXDROP+
   #:+PSYNCH_CVBROAD+
   #:+PSYNCH_CVSIGNAL+
   #:+PSYNCH_CVWAIT+
   #:+PSYNCH_RW_RDLOCK+
   #:+PSYNCH_RW_WRLOCK+
   #:+PSYNCH_RW_UNLOCK+
   #:+PSYNCH_RW_UNLOCK2+
   #:+GETSID+
   #:+SETTID_WITH_PID+
   #:+PSYNCH_CVCLRPREPOST+
   #:+AIO_FSYNC+
   #:+AIO_RETURN+
   #:+AIO_SUSPEND+
   #:+AIO_CANCEL+
   #:+AIO_ERROR+
   #:+AIO_READ+
   #:+AIO_WRITE+
   #:+LIO_LISTIO+
   #:+IOPOLICYSYS+
   #:+PROCESS_POLICY+
   #:+MLOCKALL+
   #:+MUNLOCKALL+
   #:+ISSETUGID+
   #:+__PTHREAD_KILL+
   #:+__PTHREAD_SIGMASK+
   #:+__SIGWAIT+
   #:+__DISABLE_THREADSIGNAL+
   #:+__PTHREAD_MARKCANCEL+
   #:+__PTHREAD_CANCELED+
   #:+__SEMWAIT_SIGNAL+
   #:+PROC_INFO+
   #:+SENDFILE+
   #:+STAT64+
   #:+FSTAT64+
   #:+LSTAT64+
   #:+STAT64_EXTENDED+
   #:+LSTAT64_EXTENDED+
   #:+FSTAT64_EXTENDED+
   #:+GETDIRENTRIES64+
   #:+STATFS64+
   #:+FSTATFS64+
   #:+GETFSSTAT64+
   #:+__PTHREAD_CHDIR+
   #:+__PTHREAD_FCHDIR+
   #:+AUDIT+
   #:+AUDITON+
   #:+GETAUID+
   #:+SETAUID+
   #:+GETAUDIT+
   #:+SETAUDIT+
   #:+GETAUDIT_ADDR+
   #:+SETAUDIT_ADDR+
   #:+AUDITCTL+
   #:+BSDTHREAD_CREATE+
   #:+BSDTHREAD_TERMINATE+
   #:+KQUEUE+
   #:+KEVENT+
   #:+LCHOWN+
   #:+STACK_SNAPSHOT+
   #:+BSDTHREAD_REGISTER+
   #:+WORKQ_OPEN+
   #:+WORKQ_KERNRETURN+
   #:+KEVENT64+
   #:+__OLD_SEMWAIT_SIGNAL+
   #:+__OLD_SEMWAIT_SIGNAL_NOCANCEL+
   #:+THREAD_SELFID+
   #:+__MAC_EXECVE+
   #:+__MAC_SYSCALL+
   #:+__MAC_GET_FILE+
   #:+__MAC_SET_FILE+
   #:+__MAC_GET_LINK+
   #:+__MAC_SET_LINK+
   #:+__MAC_GET_PROC+
   #:+__MAC_SET_PROC+
   #:+__MAC_GET_FD+
   #:+__MAC_SET_FD+
   #:+__MAC_GET_PID+
   #:+__MAC_GET_LCID+
   #:+__MAC_GET_LCTX+
   #:+__MAC_SET_LCTX+
   #:+SETLCID+
   #:+GETLCID+
   #:+READ_NOCANCEL+
   #:+WRITE_NOCANCEL+
   #:+OPEN_NOCANCEL+
   #:+CLOSE_NOCANCEL+
   #:+WAIT4_NOCANCEL+
   #:+RECVMSG_NOCANCEL+
   #:+SENDMSG_NOCANCEL+
   #:+RECVFROM_NOCANCEL+
   #:+ACCEPT_NOCANCEL+
   #:+MSYNC_NOCANCEL+
   #:+FCNTL_NOCANCEL+
   #:+SELECT_NOCANCEL+
   #:+FSYNC_NOCANCEL+
   #:+CONNECT_NOCANCEL+
   #:+SIGSUSPEND_NOCANCEL+
   #:+READV_NOCANCEL+
   #:+WRITEV_NOCANCEL+
   #:+SENDTO_NOCANCEL+
   #:+PREAD_NOCANCEL+
   #:+PWRITE_NOCANCEL+
   #:+WAITID_NOCANCEL+
   #:+POLL_NOCANCEL+
   #:+MSGSND_NOCANCEL+
   #:+MSGRCV_NOCANCEL+
   #:+SEM_WAIT_NOCANCEL+
   #:+AIO_SUSPEND_NOCANCEL+
   #:+__SIGWAIT_NOCANCEL+
   #:+__SEMWAIT_SIGNAL_NOCANCEL+
   #:+__MAC_MOUNT+
   #:+__MAC_GET_MOUNT+
   #:+__MAC_GETFSSTAT+
   #:+FSGETPATH+
   #:+AUDIT_SESSION_SELF+
   #:+AUDIT_SESSION_JOIN+
   #:+FILEPORT_MAKEPORT+
   #:+FILEPORT_MAKEFD+
   #:+AUDIT_SESSION_PORT+
   #:+PID_SUSPEND+
   #:+PID_RESUME+
   #:+PID_HIBERNATE+
   #:+PID_SHUTDOWN_SOCKETS+
   #:+SHARED_REGION_MAP_AND_SLIDE_NP+
   #:+MAXSYSCALL))

(in-package #:syscall.constants)

(defconstant +SYSCALL+ 0)
(defconstant +EXIT+ 1)
(defconstant +FORK+ 2)
(defconstant +READ+ 3)
(defconstant +WRITE+ 4)
(defconstant +OPEN+ 5)
(defconstant +CLOSE+ 6)
(defconstant +WAIT4+ 7)
(defconstant +LINK+ 9)
(defconstant +UNLINK+ 10)
(defconstant +CHDIR+ 12)
(defconstant +FCHDIR+ 13)
(defconstant +MKNOD+ 14)
(defconstant +CHMOD+ 15)
(defconstant +CHOWN+ 16)
(defconstant +GETFSSTAT+ 18)
(defconstant +GETPID+ 20)
(defconstant +SETUID+ 23)
(defconstant +GETUID+ 24)
(defconstant +GETEUID+ 25)
(defconstant +PTRACE+ 26)
(defconstant +RECVMSG+ 27)
(defconstant +SENDMSG+ 28)
(defconstant +RECVFROM+ 29)
(defconstant +ACCEPT+ 30)
(defconstant +GETPEERNAME+ 31)
(defconstant +GETSOCKNAME+ 32)
(defconstant +ACCESS+ 33)
(defconstant +CHFLAGS+ 34)
(defconstant +FCHFLAGS+ 35)
(defconstant +SYNC+ 36)
(defconstant +KILL+ 37)
(defconstant +GETPPID+ 39)
(defconstant +DUP+ 41)
(defconstant +PIPE+ 42)
(defconstant +GETEGID+ 43)
(defconstant +PROFIL+ 44)
(defconstant +SIGACTION+ 46)
(defconstant +GETGID+ 47)
(defconstant +SIGPROCMASK+ 48)
(defconstant +GETLOGIN+ 49)
(defconstant +SETLOGIN+ 50)
(defconstant +ACCT+ 51)
(defconstant +SIGPENDING+ 52)
(defconstant +SIGALTSTACK+ 53)
(defconstant +IOCTL+ 54)
(defconstant +REBOOT+ 55)
(defconstant +REVOKE+ 56)
(defconstant +SYMLINK+ 57)
(defconstant +READLINK+ 58)
(defconstant +EXECVE+ 59)
(defconstant +UMASK+ 60)
(defconstant +CHROOT+ 61)
(defconstant +MSYNC+ 65)
(defconstant +VFORK+ 66)
(defconstant +MUNMAP+ 73)
(defconstant +MPROTECT+ 74)
(defconstant +MADVISE+ 75)
(defconstant +MINCORE+ 78)
(defconstant +GETGROUPS+ 79)
(defconstant +SETGROUPS+ 80)
(defconstant +GETPGRP+ 81)
(defconstant +SETPGID+ 82)
(defconstant +SETITIMER+ 83)
(defconstant +SWAPON+ 85)
(defconstant +GETITIMER+ 86)
(defconstant +GETDTABLESIZE+ 89)
(defconstant +DUP2+ 90)
(defconstant +FCNTL+ 92)
(defconstant +SELECT+ 93)
(defconstant +FSYNC+ 95)
(defconstant +SETPRIORITY+ 96)
(defconstant +SOCKET+ 97)
(defconstant +CONNECT+ 98)
(defconstant +GETPRIORITY+ 100)
(defconstant +BIND+ 104)
(defconstant +SETSOCKOPT+ 105)
(defconstant +LISTEN+ 106)
(defconstant +SIGSUSPEND+ 111)
(defconstant +GETTIMEOFDAY+ 116)
(defconstant +GETRUSAGE+ 117)
(defconstant +GETSOCKOPT+ 118)
(defconstant +READV+ 120)
(defconstant +WRITEV+ 121)
(defconstant +SETTIMEOFDAY+ 122)
(defconstant +FCHOWN+ 123)
(defconstant +FCHMOD+ 124)
(defconstant +SETREUID+ 126)
(defconstant +SETREGID+ 127)
(defconstant +RENAME+ 128)
(defconstant +FLOCK+ 131)
(defconstant +MKFIFO+ 132)
(defconstant +SENDTO+ 133)
(defconstant +SHUTDOWN+ 134)
(defconstant +SOCKETPAIR+ 135)
(defconstant +MKDIR+ 136)
(defconstant +RMDIR+ 137)
(defconstant +UTIMES+ 138)
(defconstant +FUTIMES+ 139)
(defconstant +ADJTIME+ 140)
(defconstant +GETHOSTUUID+ 142)
(defconstant +SETSID+ 147)
(defconstant +GETPGID+ 151)
(defconstant +SETPRIVEXEC+ 152)
(defconstant +PREAD+ 153)
(defconstant +PWRITE+ 154)
(defconstant +NFSSVC+ 155)
(defconstant +STATFS+ 157)
(defconstant +FSTATFS+ 158)
(defconstant +UNMOUNT+ 159)
(defconstant +GETFH+ 161)
(defconstant +QUOTACTL+ 165)
(defconstant +MOUNT+ 167)
(defconstant +CSOPS+ 169)
(defconstant +WAITID+ 173)
(defconstant +ADD_PROFIL+ 176)
(defconstant +KDEBUG_TRACE+ 180)
(defconstant +SETGID+ 181)
(defconstant +SETEGID+ 182)
(defconstant +SETEUID+ 183)
(defconstant +SIGRETURN+ 184)
(defconstant +CHUD+ 185)
(defconstant +FDATASYNC+ 187)
(defconstant +STAT+ 188)
(defconstant +FSTAT+ 189)
(defconstant +LSTAT+ 190)
(defconstant +PATHCONF+ 191)
(defconstant +FPATHCONF+ 192)
(defconstant +GETRLIMIT+ 194)
(defconstant +SETRLIMIT+ 195)
(defconstant +GETDIRENTRIES+ 196)
(defconstant +MMAP+ 197)
(defconstant +LSEEK+ 199)
(defconstant +TRUNCATE+ 200)
(defconstant +FTRUNCATE+ 201)
(defconstant +__SYSCTL+ 202)
(defconstant +MLOCK+ 203)
(defconstant +MUNLOCK+ 204)
(defconstant +UNDELETE+ 205)
(defconstant +ATSOCKET+ 206)
(defconstant +ATGETMSG+ 207)
(defconstant +ATPUTMSG+ 208)
(defconstant +ATPSNDREQ+ 209)
(defconstant +ATPSNDRSP+ 210)
(defconstant +ATPGETREQ+ 211)
(defconstant +ATPGETRSP+ 212)
(defconstant +MKCOMPLEX+ 216)
(defconstant +STATV+ 217)
(defconstant +LSTATV+ 218)
(defconstant +FSTATV+ 219)
(defconstant +GETATTRLIST+ 220)
(defconstant +SETATTRLIST+ 221)
(defconstant +GETDIRENTRIESATTR+ 222)
(defconstant +EXCHANGEDATA+ 223)
(defconstant +SEARCHFS+ 225)
(defconstant +DELETE+ 226)
(defconstant +COPYFILE+ 227)
(defconstant +FGETATTRLIST+ 228)
(defconstant +FSETATTRLIST+ 229)
(defconstant +POLL+ 230)
(defconstant +WATCHEVENT+ 231)
(defconstant +WAITEVENT+ 232)
(defconstant +MODWATCH+ 233)
(defconstant +GETXATTR+ 234)
(defconstant +FGETXATTR+ 235)
(defconstant +SETXATTR+ 236)
(defconstant +FSETXATTR+ 237)
(defconstant +REMOVEXATTR+ 238)
(defconstant +FREMOVEXATTR+ 239)
(defconstant +LISTXATTR+ 240)
(defconstant +FLISTXATTR+ 241)
(defconstant +FSCTL+ 242)
(defconstant +INITGROUPS+ 243)
(defconstant +POSIX_SPAWN+ 244)
(defconstant +FFSCTL+ 245)
(defconstant +NFSCLNT+ 247)
(defconstant +FHOPEN+ 248)
(defconstant +MINHERIT+ 250)
(defconstant +SEMSYS+ 251)
(defconstant +MSGSYS+ 252)
(defconstant +SHMSYS+ 253)
(defconstant +SEMCTL+ 254)
(defconstant +SEMGET+ 255)
(defconstant +SEMOP+ 256)
(defconstant +MSGCTL+ 258)
(defconstant +MSGGET+ 259)
(defconstant +MSGSND+ 260)
(defconstant +MSGRCV+ 261)
(defconstant +SHMAT+ 262)
(defconstant +SHMCTL+ 263)
(defconstant +SHMDT+ 264)
(defconstant +SHMGET+ 265)
(defconstant +SHM_OPEN+ 266)
(defconstant +SHM_UNLINK+ 267)
(defconstant +SEM_OPEN+ 268)
(defconstant +SEM_CLOSE+ 269)
(defconstant +SEM_UNLINK+ 270)
(defconstant +SEM_WAIT+ 271)
(defconstant +SEM_TRYWAIT+ 272)
(defconstant +SEM_POST+ 273)
(defconstant +SEM_GETVALUE+ 274)
(defconstant +SEM_INIT+ 275)
(defconstant +SEM_DESTROY+ 276)
(defconstant +OPEN_EXTENDED+ 277)
(defconstant +UMASK_EXTENDED+ 278)
(defconstant +STAT_EXTENDED+ 279)
(defconstant +LSTAT_EXTENDED+ 280)
(defconstant +FSTAT_EXTENDED+ 281)
(defconstant +CHMOD_EXTENDED+ 282)
(defconstant +FCHMOD_EXTENDED+ 283)
(defconstant +ACCESS_EXTENDED+ 284)
(defconstant +SETTID+ 285)
(defconstant +GETTID+ 286)
(defconstant +SETSGROUPS+ 287)
(defconstant +GETSGROUPS+ 288)
(defconstant +SETWGROUPS+ 289)
(defconstant +GETWGROUPS+ 290)
(defconstant +MKFIFO_EXTENDED+ 291)
(defconstant +MKDIR_EXTENDED+ 292)
(defconstant +IDENTITYSVC+ 293)
(defconstant +SHARED_REGION_CHECK_NP+ 294)
(defconstant +VM_PRESSURE_MONITOR+ 296)
(defconstant +PSYNCH_RW_LONGRDLOCK+ 297)
(defconstant +PSYNCH_RW_YIELDWRLOCK+ 298)
(defconstant +PSYNCH_RW_DOWNGRADE+ 299)
(defconstant +PSYNCH_RW_UPGRADE+ 300)
(defconstant +PSYNCH_MUTEXWAIT+ 301)
(defconstant +PSYNCH_MUTEXDROP+ 302)
(defconstant +PSYNCH_CVBROAD+ 303)
(defconstant +PSYNCH_CVSIGNAL+ 304)
(defconstant +PSYNCH_CVWAIT+ 305)
(defconstant +PSYNCH_RW_RDLOCK+ 306)
(defconstant +PSYNCH_RW_WRLOCK+ 307)
(defconstant +PSYNCH_RW_UNLOCK+ 308)
(defconstant +PSYNCH_RW_UNLOCK2+ 309)
(defconstant +GETSID+ 310)
(defconstant +SETTID_WITH_PID+ 311)
(defconstant +PSYNCH_CVCLRPREPOST+ 312)
(defconstant +AIO_FSYNC+ 313)
(defconstant +AIO_RETURN+ 314)
(defconstant +AIO_SUSPEND+ 315)
(defconstant +AIO_CANCEL+ 316)
(defconstant +AIO_ERROR+ 317)
(defconstant +AIO_READ+ 318)
(defconstant +AIO_WRITE+ 319)
(defconstant +LIO_LISTIO+ 320)
(defconstant +IOPOLICYSYS+ 322)
(defconstant +PROCESS_POLICY+ 323)
(defconstant +MLOCKALL+ 324)
(defconstant +MUNLOCKALL+ 325)
(defconstant +ISSETUGID+ 327)
(defconstant +__PTHREAD_KILL+ 328)
(defconstant +__PTHREAD_SIGMASK+ 329)
(defconstant +__SIGWAIT+ 330)
(defconstant +__DISABLE_THREADSIGNAL+ 331)
(defconstant +__PTHREAD_MARKCANCEL+ 332)
(defconstant +__PTHREAD_CANCELED+ 333)
(defconstant +__SEMWAIT_SIGNAL+ 334)
(defconstant +PROC_INFO+ 336)
(defconstant +SENDFILE+ 337)
(defconstant +STAT64+ 338)
(defconstant +FSTAT64+ 339)
(defconstant +LSTAT64+ 340)
(defconstant +STAT64_EXTENDED+ 341)
(defconstant +LSTAT64_EXTENDED+ 342)
(defconstant +FSTAT64_EXTENDED+ 343)
(defconstant +GETDIRENTRIES64+ 344)
(defconstant +STATFS64+ 345)
(defconstant +FSTATFS64+ 346)
(defconstant +GETFSSTAT64+ 347)
(defconstant +__PTHREAD_CHDIR+ 348)
(defconstant +__PTHREAD_FCHDIR+ 349)
(defconstant +AUDIT+ 350)
(defconstant +AUDITON+ 351)
(defconstant +GETAUID+ 353)
(defconstant +SETAUID+ 354)
(defconstant +GETAUDIT+ 355)
(defconstant +SETAUDIT+ 356)
(defconstant +GETAUDIT_ADDR+ 357)
(defconstant +SETAUDIT_ADDR+ 358)
(defconstant +AUDITCTL+ 359)
(defconstant +BSDTHREAD_CREATE+ 360)
(defconstant +BSDTHREAD_TERMINATE+ 361)
(defconstant +KQUEUE+ 362)
(defconstant +KEVENT+ 363)
(defconstant +LCHOWN+ 364)
(defconstant +STACK_SNAPSHOT+ 365)
(defconstant +BSDTHREAD_REGISTER+ 366)
(defconstant +WORKQ_OPEN+ 367)
(defconstant +WORKQ_KERNRETURN+ 368)
(defconstant +KEVENT64+ 369)
(defconstant +__OLD_SEMWAIT_SIGNAL+ 370)
(defconstant +__OLD_SEMWAIT_SIGNAL_NOCANCEL+ 371)
(defconstant +THREAD_SELFID+ 372)
(defconstant +__MAC_EXECVE+ 380)
(defconstant +__MAC_SYSCALL+ 381)
(defconstant +__MAC_GET_FILE+ 382)
(defconstant +__MAC_SET_FILE+ 383)
(defconstant +__MAC_GET_LINK+ 384)
(defconstant +__MAC_SET_LINK+ 385)
(defconstant +__MAC_GET_PROC+ 386)
(defconstant +__MAC_SET_PROC+ 387)
(defconstant +__MAC_GET_FD+ 388)
(defconstant +__MAC_SET_FD+ 389)
(defconstant +__MAC_GET_PID+ 390)
(defconstant +__MAC_GET_LCID+ 391)
(defconstant +__MAC_GET_LCTX+ 392)
(defconstant +__MAC_SET_LCTX+ 393)
(defconstant +SETLCID+ 394)
(defconstant +GETLCID+ 395)
(defconstant +READ_NOCANCEL+ 396)
(defconstant +WRITE_NOCANCEL+ 397)
(defconstant +OPEN_NOCANCEL+ 398)
(defconstant +CLOSE_NOCANCEL+ 399)
(defconstant +WAIT4_NOCANCEL+ 400)
(defconstant +RECVMSG_NOCANCEL+ 401)
(defconstant +SENDMSG_NOCANCEL+ 402)
(defconstant +RECVFROM_NOCANCEL+ 403)
(defconstant +ACCEPT_NOCANCEL+ 404)
(defconstant +MSYNC_NOCANCEL+ 405)
(defconstant +FCNTL_NOCANCEL+ 406)
(defconstant +SELECT_NOCANCEL+ 407)
(defconstant +FSYNC_NOCANCEL+ 408)
(defconstant +CONNECT_NOCANCEL+ 409)
(defconstant +SIGSUSPEND_NOCANCEL+ 410)
(defconstant +READV_NOCANCEL+ 411)
(defconstant +WRITEV_NOCANCEL+ 412)
(defconstant +SENDTO_NOCANCEL+ 413)
(defconstant +PREAD_NOCANCEL+ 414)
(defconstant +PWRITE_NOCANCEL+ 415)
(defconstant +WAITID_NOCANCEL+ 416)
(defconstant +POLL_NOCANCEL+ 417)
(defconstant +MSGSND_NOCANCEL+ 418)
(defconstant +MSGRCV_NOCANCEL+ 419)
(defconstant +SEM_WAIT_NOCANCEL+ 420)
(defconstant +AIO_SUSPEND_NOCANCEL+ 421)
(defconstant +__SIGWAIT_NOCANCEL+ 422)
(defconstant +__SEMWAIT_SIGNAL_NOCANCEL+ 423)
(defconstant +__MAC_MOUNT+ 424)
(defconstant +__MAC_GET_MOUNT+ 425)
(defconstant +__MAC_GETFSSTAT+ 426)
(defconstant +FSGETPATH+ 427)
(defconstant +AUDIT_SESSION_SELF+ 428)
(defconstant +AUDIT_SESSION_JOIN+ 429)
(defconstant +FILEPORT_MAKEPORT+ 430)
(defconstant +FILEPORT_MAKEFD+ 431)
(defconstant +AUDIT_SESSION_PORT+ 432)
(defconstant +PID_SUSPEND+ 433)
(defconstant +PID_RESUME+ 434)
(defconstant +PID_HIBERNATE+ 435)
(defconstant +PID_SHUTDOWN_SOCKETS+ 436)
(defconstant +SHARED_REGION_MAP_AND_SLIDE_NP+ 438)
(defconstant +MAXSYSCALL+ 439)
