;;;; constants.lisp
;;;; DO NOT MODIFY - this file is automatically generated
(in-package #:cl-user)

(defpackage syscall.constants
  (:use #:cl)
  (:export
   #:+IO_SETUP+
   #:+IO_DESTROY+
   #:+IO_SUBMIT+
   #:+IO_CANCEL+
   #:+IO_GETEVENTS+
   #:+SETXATTR+
   #:+LSETXATTR+
   #:+FSETXATTR+
   #:+GETXATTR+
   #:+LGETXATTR+
   #:+FGETXATTR+
   #:+LISTXATTR+
   #:+LLISTXATTR+
   #:+FLISTXATTR+
   #:+REMOVEXATTR+
   #:+LREMOVEXATTR+
   #:+FREMOVEXATTR+
   #:+GETCWD+
   #:+LOOKUP_DCOOKIE+
   #:+EVENTFD2+
   #:+EPOLL_CREATE1+
   #:+EPOLL_CTL+
   #:+EPOLL_PWAIT+
   #:+DUP+
   #:+DUP3+
   #:+FCNTL+
   #:+INOTIFY_INIT1+
   #:+INOTIFY_ADD_WATCH+
   #:+INOTIFY_RM_WATCH+
   #:+IOCTL+
   #:+IOPRIO_SET+
   #:+IOPRIO_GET+
   #:+FLOCK+
   #:+MKNODAT+
   #:+MKDIRAT+
   #:+UNLINKAT+
   #:+SYMLINKAT+
   #:+LINKAT+
   #:+RENAMEAT+
   #:+UMOUNT2+
   #:+MOUNT+
   #:+PIVOT_ROOT+
   #:+NFSSERVCTL+
   #:+STATFS+
   #:+FSTATFS+
   #:+TRUNCATE+
   #:+FTRUNCATE+
   #:+FALLOCATE+
   #:+FACCESSAT+
   #:+CHDIR+
   #:+FCHDIR+
   #:+CHROOT+
   #:+FCHMOD+
   #:+FCHMODAT+
   #:+FCHOWNAT+
   #:+FCHOWN+
   #:+OPENAT+
   #:+CLOSE+
   #:+VHANGUP+
   #:+PIPE2+
   #:+QUOTACTL+
   #:+GETDENTS64+
   #:+LSEEK+
   #:+READ+
   #:+WRITE+
   #:+READV+
   #:+WRITEV+
   #:+PREAD64+
   #:+PWRITE64+
   #:+PREADV+
   #:+PWRITEV+
   #:+SENDFILE+
   #:+PSELECT6+
   #:+PPOLL+
   #:+SIGNALFD4+
   #:+VMSPLICE+
   #:+SPLICE+
   #:+TEE+
   #:+READLINKAT+
   #:+NEWFSTATAT+
   #:+FSTAT+
   #:+SYNC+
   #:+FSYNC+
   #:+FDATASYNC+
   #:+SYNC_FILE_RANGE+
   #:+TIMERFD_CREATE+
   #:+TIMERFD_SETTIME+
   #:+TIMERFD_GETTIME+
   #:+UTIMENSAT+
   #:+ACCT+
   #:+CAPGET+
   #:+CAPSET+
   #:+PERSONALITY+
   #:+EXIT+
   #:+EXIT_GROUP+
   #:+WAITID+
   #:+SET_TID_ADDRESS+
   #:+UNSHARE+
   #:+FUTEX+
   #:+SET_ROBUST_LIST+
   #:+GET_ROBUST_LIST+
   #:+NANOSLEEP+
   #:+GETITIMER+
   #:+SETITIMER+
   #:+KEXEC_LOAD+
   #:+INIT_MODULE+
   #:+DELETE_MODULE+
   #:+TIMER_CREATE+
   #:+TIMER_GETTIME+
   #:+TIMER_GETOVERRUN+
   #:+TIMER_SETTIME+
   #:+TIMER_DELETE+
   #:+CLOCK_SETTIME+
   #:+CLOCK_GETTIME+
   #:+CLOCK_GETRES+
   #:+CLOCK_NANOSLEEP+
   #:+SYSLOG+
   #:+PTRACE+
   #:+SCHED_SETPARAM+
   #:+SCHED_SETSCHEDULER+
   #:+SCHED_GETSCHEDULER+
   #:+SCHED_GETPARAM+
   #:+SCHED_SETAFFINITY+
   #:+SCHED_GETAFFINITY+
   #:+SCHED_YIELD+
   #:+SCHED_GET_PRIORITY_MAX+
   #:+SCHED_GET_PRIORITY_MIN+
   #:+SCHED_RR_GET_INTERVAL+
   #:+RESTART_SYSCALL+
   #:+KILL+
   #:+TKILL+
   #:+TGKILL+
   #:+SIGALTSTACK+
   #:+RT_SIGSUSPEND+
   #:+RT_SIGACTION+
   #:+RT_SIGPROCMASK+
   #:+RT_SIGPENDING+
   #:+RT_SIGTIMEDWAIT+
   #:+RT_SIGQUEUEINFO+
   #:+RT_SIGRETURN+
   #:+SETPRIORITY+
   #:+GETPRIORITY+
   #:+REBOOT+
   #:+SETREGID+
   #:+SETGID+
   #:+SETREUID+
   #:+SETUID+
   #:+SETRESUID+
   #:+GETRESUID+
   #:+SETRESGID+
   #:+GETRESGID+
   #:+SETFSUID+
   #:+SETFSGID+
   #:+TIMES+
   #:+SETPGID+
   #:+GETPGID+
   #:+GETSID+
   #:+SETSID+
   #:+GETGROUPS+
   #:+SETGROUPS+
   #:+UNAME+
   #:+SETHOSTNAME+
   #:+SETDOMAINNAME+
   #:+GETRLIMIT+
   #:+SETRLIMIT+
   #:+GETRUSAGE+
   #:+UMASK+
   #:+PRCTL+
   #:+GETCPU+
   #:+GETTIMEOFDAY+
   #:+SETTIMEOFDAY+
   #:+ADJTIMEX+
   #:+GETPID+
   #:+GETPPID+
   #:+GETUID+
   #:+GETEUID+
   #:+GETGID+
   #:+GETEGID+
   #:+GETTID+
   #:+SYSINFO+
   #:+MQ_OPEN+
   #:+MQ_UNLINK+
   #:+MQ_TIMEDSEND+
   #:+MQ_TIMEDRECEIVE+
   #:+MQ_NOTIFY+
   #:+MQ_GETSETATTR+
   #:+MSGGET+
   #:+MSGCTL+
   #:+MSGRCV+
   #:+MSGSND+
   #:+SEMGET+
   #:+SEMCTL+
   #:+SEMTIMEDOP+
   #:+SEMOP+
   #:+SHMGET+
   #:+SHMCTL+
   #:+SHMAT+
   #:+SHMDT+
   #:+SOCKET+
   #:+SOCKETPAIR+
   #:+BIND+
   #:+LISTEN+
   #:+ACCEPT+
   #:+CONNECT+
   #:+GETSOCKNAME+
   #:+GETPEERNAME+
   #:+SENDTO+
   #:+RECVFROM+
   #:+SETSOCKOPT+
   #:+GETSOCKOPT+
   #:+SHUTDOWN+
   #:+SENDMSG+
   #:+RECVMSG+
   #:+READAHEAD+
   #:+BRK+
   #:+MUNMAP+
   #:+MREMAP+
   #:+ADD_KEY+
   #:+REQUEST_KEY+
   #:+KEYCTL+
   #:+CLONE+
   #:+EXECVE+
   #:+MMAP+
   #:+FADVISE64+
   #:+SWAPON+
   #:+SWAPOFF+
   #:+MPROTECT+
   #:+MSYNC+
   #:+MLOCK+
   #:+MUNLOCK+
   #:+MLOCKALL+
   #:+MUNLOCKALL+
   #:+MINCORE+
   #:+MADVISE+
   #:+REMAP_FILE_PAGES+
   #:+MBIND+
   #:+GET_MEMPOLICY+
   #:+SET_MEMPOLICY+
   #:+MIGRATE_PAGES+
   #:+MOVE_PAGES+
   #:+RT_TGSIGQUEUEINFO+
   #:+PERF_EVENT_OPEN+
   #:+ACCEPT4+
   #:+RECVMMSG+
   #:+ARCH_SPECIFIC_SYSCALL+
   #:+WAIT4+
   #:+PRLIMIT64+
   #:+FANOTIFY_INIT+
   #:+FANOTIFY_MARK+
   #:+NAME_TO_HANDLE_AT+
   #:+OPEN_BY_HANDLE_AT+
   #:+CLOCK_ADJTIME+
   #:+SYNCFS+
   #:+SETNS+
   #:+SENDMMSG+
   #:+PROCESS_VM_READV+
   #:+PROCESS_VM_WRITEV+
   #:+KCMP+
   #:+FINIT_MODULE+
   #:+SCHED_SETATTR+
   #:+SCHED_GETATTR+
   #:+RENAMEAT2+
   #:+SECCOMP+
   #:+GETRANDOM+
   #:+MEMFD_CREATE+
   #:+BPF+
   #:+EXECVEAT+
   #:+USERFAULTFD+
   #:+MEMBARRIER+
   #:+MLOCK2+
   #:+COPY_FILE_RANGE+
   #:+PREADV2+
   #:+PWRITEV2+
   #:+PKEY_MPROTECT+
   #:+PKEY_ALLOC+
   #:+PKEY_FREE+
   #:+STATX+
   #:+IO_PGETEVENTS+
   #:+RSEQ+
   #:+KEXEC_FILE_LOAD+
   #:+PIDFD_SEND_SIGNAL+
   #:+IO_URING_SETUP+
   #:+IO_URING_ENTER+
   #:+IO_URING_REGISTER+
   #:+OPEN_TREE+
   #:+MOVE_MOUNT+
   #:+FSOPEN+
   #:+FSCONFIG+
   #:+FSMOUNT+
   #:+FSPICK+
   #:+PIDFD_OPEN+
   #:+CLONE3+
   #:+CLOSE_RANGE+
   #:+OPENAT2+
   #:+PIDFD_GETFD+
   #:+FACCESSAT2+
   #:+PROCESS_MADVISE+
   #:+EPOLL_PWAIT2+
   #:+MOUNT_SETATTR+
   #:+SYSCALLS+))

(in-package #:syscall.constants)

(defconstant +IO_SETUP+ 0)
(defconstant +IO_DESTROY+ 1)
(defconstant +IO_SUBMIT+ 2)
(defconstant +IO_CANCEL+ 3)
(defconstant +IO_GETEVENTS+ 4)
(defconstant +SETXATTR+ 5)
(defconstant +LSETXATTR+ 6)
(defconstant +FSETXATTR+ 7)
(defconstant +GETXATTR+ 8)
(defconstant +LGETXATTR+ 9)
(defconstant +FGETXATTR+ 10)
(defconstant +LISTXATTR+ 11)
(defconstant +LLISTXATTR+ 12)
(defconstant +FLISTXATTR+ 13)
(defconstant +REMOVEXATTR+ 14)
(defconstant +LREMOVEXATTR+ 15)
(defconstant +FREMOVEXATTR+ 16)
(defconstant +GETCWD+ 17)
(defconstant +LOOKUP_DCOOKIE+ 18)
(defconstant +EVENTFD2+ 19)
(defconstant +EPOLL_CREATE1+ 20)
(defconstant +EPOLL_CTL+ 21)
(defconstant +EPOLL_PWAIT+ 22)
(defconstant +DUP+ 23)
(defconstant +DUP3+ 24)
(defconstant +FCNTL+ 25)
(defconstant +INOTIFY_INIT1+ 26)
(defconstant +INOTIFY_ADD_WATCH+ 27)
(defconstant +INOTIFY_RM_WATCH+ 28)
(defconstant +IOCTL+ 29)
(defconstant +IOPRIO_SET+ 30)
(defconstant +IOPRIO_GET+ 31)
(defconstant +FLOCK+ 32)
(defconstant +MKNODAT+ 33)
(defconstant +MKDIRAT+ 34)
(defconstant +UNLINKAT+ 35)
(defconstant +SYMLINKAT+ 36)
(defconstant +LINKAT+ 37)
(defconstant +RENAMEAT+ 38)
(defconstant +UMOUNT2+ 39)
(defconstant +MOUNT+ 40)
(defconstant +PIVOT_ROOT+ 41)
(defconstant +NFSSERVCTL+ 42)
(defconstant +STATFS+ 43)
(defconstant +FSTATFS+ 44)
(defconstant +TRUNCATE+ 45)
(defconstant +FTRUNCATE+ 46)
(defconstant +FALLOCATE+ 47)
(defconstant +FACCESSAT+ 48)
(defconstant +CHDIR+ 49)
(defconstant +FCHDIR+ 50)
(defconstant +CHROOT+ 51)
(defconstant +FCHMOD+ 52)
(defconstant +FCHMODAT+ 53)
(defconstant +FCHOWNAT+ 54)
(defconstant +FCHOWN+ 55)
(defconstant +OPENAT+ 56)
(defconstant +CLOSE+ 57)
(defconstant +VHANGUP+ 58)
(defconstant +PIPE2+ 59)
(defconstant +QUOTACTL+ 60)
(defconstant +GETDENTS64+ 61)
(defconstant +LSEEK+ 62)
(defconstant +READ+ 63)
(defconstant +WRITE+ 64)
(defconstant +READV+ 65)
(defconstant +WRITEV+ 66)
(defconstant +PREAD64+ 67)
(defconstant +PWRITE64+ 68)
(defconstant +PREADV+ 69)
(defconstant +PWRITEV+ 70)
(defconstant +SENDFILE+ 71)
(defconstant +PSELECT6+ 72)
(defconstant +PPOLL+ 73)
(defconstant +SIGNALFD4+ 74)
(defconstant +VMSPLICE+ 75)
(defconstant +SPLICE+ 76)
(defconstant +TEE+ 77)
(defconstant +READLINKAT+ 78)
(defconstant +NEWFSTATAT+ 79)
(defconstant +FSTAT+ 80)
(defconstant +SYNC+ 81)
(defconstant +FSYNC+ 82)
(defconstant +FDATASYNC+ 83)
(defconstant +SYNC_FILE_RANGE+ 84)
(defconstant +TIMERFD_CREATE+ 85)
(defconstant +TIMERFD_SETTIME+ 86)
(defconstant +TIMERFD_GETTIME+ 87)
(defconstant +UTIMENSAT+ 88)
(defconstant +ACCT+ 89)
(defconstant +CAPGET+ 90)
(defconstant +CAPSET+ 91)
(defconstant +PERSONALITY+ 92)
(defconstant +EXIT+ 93)
(defconstant +EXIT_GROUP+ 94)
(defconstant +WAITID+ 95)
(defconstant +SET_TID_ADDRESS+ 96)
(defconstant +UNSHARE+ 97)
(defconstant +FUTEX+ 98)
(defconstant +SET_ROBUST_LIST+ 99)
(defconstant +GET_ROBUST_LIST+ 100)
(defconstant +NANOSLEEP+ 101)
(defconstant +GETITIMER+ 102)
(defconstant +SETITIMER+ 103)
(defconstant +KEXEC_LOAD+ 104)
(defconstant +INIT_MODULE+ 105)
(defconstant +DELETE_MODULE+ 106)
(defconstant +TIMER_CREATE+ 107)
(defconstant +TIMER_GETTIME+ 108)
(defconstant +TIMER_GETOVERRUN+ 109)
(defconstant +TIMER_SETTIME+ 110)
(defconstant +TIMER_DELETE+ 111)
(defconstant +CLOCK_SETTIME+ 112)
(defconstant +CLOCK_GETTIME+ 113)
(defconstant +CLOCK_GETRES+ 114)
(defconstant +CLOCK_NANOSLEEP+ 115)
(defconstant +SYSLOG+ 116)
(defconstant +PTRACE+ 117)
(defconstant +SCHED_SETPARAM+ 118)
(defconstant +SCHED_SETSCHEDULER+ 119)
(defconstant +SCHED_GETSCHEDULER+ 120)
(defconstant +SCHED_GETPARAM+ 121)
(defconstant +SCHED_SETAFFINITY+ 122)
(defconstant +SCHED_GETAFFINITY+ 123)
(defconstant +SCHED_YIELD+ 124)
(defconstant +SCHED_GET_PRIORITY_MAX+ 125)
(defconstant +SCHED_GET_PRIORITY_MIN+ 126)
(defconstant +SCHED_RR_GET_INTERVAL+ 127)
(defconstant +RESTART_SYSCALL+ 128)
(defconstant +KILL+ 129)
(defconstant +TKILL+ 130)
(defconstant +TGKILL+ 131)
(defconstant +SIGALTSTACK+ 132)
(defconstant +RT_SIGSUSPEND+ 133)
(defconstant +RT_SIGACTION+ 134)
(defconstant +RT_SIGPROCMASK+ 135)
(defconstant +RT_SIGPENDING+ 136)
(defconstant +RT_SIGTIMEDWAIT+ 137)
(defconstant +RT_SIGQUEUEINFO+ 138)
(defconstant +RT_SIGRETURN+ 139)
(defconstant +SETPRIORITY+ 140)
(defconstant +GETPRIORITY+ 141)
(defconstant +REBOOT+ 142)
(defconstant +SETREGID+ 143)
(defconstant +SETGID+ 144)
(defconstant +SETREUID+ 145)
(defconstant +SETUID+ 146)
(defconstant +SETRESUID+ 147)
(defconstant +GETRESUID+ 148)
(defconstant +SETRESGID+ 149)
(defconstant +GETRESGID+ 150)
(defconstant +SETFSUID+ 151)
(defconstant +SETFSGID+ 152)
(defconstant +TIMES+ 153)
(defconstant +SETPGID+ 154)
(defconstant +GETPGID+ 155)
(defconstant +GETSID+ 156)
(defconstant +SETSID+ 157)
(defconstant +GETGROUPS+ 158)
(defconstant +SETGROUPS+ 159)
(defconstant +UNAME+ 160)
(defconstant +SETHOSTNAME+ 161)
(defconstant +SETDOMAINNAME+ 162)
(defconstant +GETRLIMIT+ 163)
(defconstant +SETRLIMIT+ 164)
(defconstant +GETRUSAGE+ 165)
(defconstant +UMASK+ 166)
(defconstant +PRCTL+ 167)
(defconstant +GETCPU+ 168)
(defconstant +GETTIMEOFDAY+ 169)
(defconstant +SETTIMEOFDAY+ 170)
(defconstant +ADJTIMEX+ 171)
(defconstant +GETPID+ 172)
(defconstant +GETPPID+ 173)
(defconstant +GETUID+ 174)
(defconstant +GETEUID+ 175)
(defconstant +GETGID+ 176)
(defconstant +GETEGID+ 177)
(defconstant +GETTID+ 178)
(defconstant +SYSINFO+ 179)
(defconstant +MQ_OPEN+ 180)
(defconstant +MQ_UNLINK+ 181)
(defconstant +MQ_TIMEDSEND+ 182)
(defconstant +MQ_TIMEDRECEIVE+ 183)
(defconstant +MQ_NOTIFY+ 184)
(defconstant +MQ_GETSETATTR+ 185)
(defconstant +MSGGET+ 186)
(defconstant +MSGCTL+ 187)
(defconstant +MSGRCV+ 188)
(defconstant +MSGSND+ 189)
(defconstant +SEMGET+ 190)
(defconstant +SEMCTL+ 191)
(defconstant +SEMTIMEDOP+ 192)
(defconstant +SEMOP+ 193)
(defconstant +SHMGET+ 194)
(defconstant +SHMCTL+ 195)
(defconstant +SHMAT+ 196)
(defconstant +SHMDT+ 197)
(defconstant +SOCKET+ 198)
(defconstant +SOCKETPAIR+ 199)
(defconstant +BIND+ 200)
(defconstant +LISTEN+ 201)
(defconstant +ACCEPT+ 202)
(defconstant +CONNECT+ 203)
(defconstant +GETSOCKNAME+ 204)
(defconstant +GETPEERNAME+ 205)
(defconstant +SENDTO+ 206)
(defconstant +RECVFROM+ 207)
(defconstant +SETSOCKOPT+ 208)
(defconstant +GETSOCKOPT+ 209)
(defconstant +SHUTDOWN+ 210)
(defconstant +SENDMSG+ 211)
(defconstant +RECVMSG+ 212)
(defconstant +READAHEAD+ 213)
(defconstant +BRK+ 214)
(defconstant +MUNMAP+ 215)
(defconstant +MREMAP+ 216)
(defconstant +ADD_KEY+ 217)
(defconstant +REQUEST_KEY+ 218)
(defconstant +KEYCTL+ 219)
(defconstant +CLONE+ 220)
(defconstant +EXECVE+ 221)
(defconstant +MMAP+ 222)
(defconstant +FADVISE64+ 223)
(defconstant +SWAPON+ 224)
(defconstant +SWAPOFF+ 225)
(defconstant +MPROTECT+ 226)
(defconstant +MSYNC+ 227)
(defconstant +MLOCK+ 228)
(defconstant +MUNLOCK+ 229)
(defconstant +MLOCKALL+ 230)
(defconstant +MUNLOCKALL+ 231)
(defconstant +MINCORE+ 232)
(defconstant +MADVISE+ 233)
(defconstant +REMAP_FILE_PAGES+ 234)
(defconstant +MBIND+ 235)
(defconstant +GET_MEMPOLICY+ 236)
(defconstant +SET_MEMPOLICY+ 237)
(defconstant +MIGRATE_PAGES+ 238)
(defconstant +MOVE_PAGES+ 239)
(defconstant +RT_TGSIGQUEUEINFO+ 240)
(defconstant +PERF_EVENT_OPEN+ 241)
(defconstant +ACCEPT4+ 242)
(defconstant +RECVMMSG+ 243)
(defconstant +ARCH_SPECIFIC_SYSCALL+ 244)
(defconstant +WAIT4+ 260)
(defconstant +PRLIMIT64+ 261)
(defconstant +FANOTIFY_INIT+ 262)
(defconstant +FANOTIFY_MARK+ 263)
(defconstant +NAME_TO_HANDLE_AT+ 264)
(defconstant +OPEN_BY_HANDLE_AT+ 265)
(defconstant +CLOCK_ADJTIME+ 266)
(defconstant +SYNCFS+ 267)
(defconstant +SETNS+ 268)
(defconstant +SENDMMSG+ 269)
(defconstant +PROCESS_VM_READV+ 270)
(defconstant +PROCESS_VM_WRITEV+ 271)
(defconstant +KCMP+ 272)
(defconstant +FINIT_MODULE+ 273)
(defconstant +SCHED_SETATTR+ 274)
(defconstant +SCHED_GETATTR+ 275)
(defconstant +RENAMEAT2+ 276)
(defconstant +SECCOMP+ 277)
(defconstant +GETRANDOM+ 278)
(defconstant +MEMFD_CREATE+ 279)
(defconstant +BPF+ 280)
(defconstant +EXECVEAT+ 281)
(defconstant +USERFAULTFD+ 282)
(defconstant +MEMBARRIER+ 283)
(defconstant +MLOCK2+ 284)
(defconstant +COPY_FILE_RANGE+ 285)
(defconstant +PREADV2+ 286)
(defconstant +PWRITEV2+ 287)
(defconstant +PKEY_MPROTECT+ 288)
(defconstant +PKEY_ALLOC+ 289)
(defconstant +PKEY_FREE+ 290)
(defconstant +STATX+ 291)
(defconstant +IO_PGETEVENTS+ 292)
(defconstant +RSEQ+ 293)
(defconstant +KEXEC_FILE_LOAD+ 294)
(defconstant +PIDFD_SEND_SIGNAL+ 424)
(defconstant +IO_URING_SETUP+ 425)
(defconstant +IO_URING_ENTER+ 426)
(defconstant +IO_URING_REGISTER+ 427)
(defconstant +OPEN_TREE+ 428)
(defconstant +MOVE_MOUNT+ 429)
(defconstant +FSOPEN+ 430)
(defconstant +FSCONFIG+ 431)
(defconstant +FSMOUNT+ 432)
(defconstant +FSPICK+ 433)
(defconstant +PIDFD_OPEN+ 434)
(defconstant +CLONE3+ 435)
(defconstant +CLOSE_RANGE+ 436)
(defconstant +OPENAT2+ 437)
(defconstant +PIDFD_GETFD+ 438)
(defconstant +FACCESSAT2+ 439)
(defconstant +PROCESS_MADVISE+ 440)
(defconstant +EPOLL_PWAIT2+ 441)
(defconstant +MOUNT_SETATTR+ 442)
(defconstant +SYSCALLS+ 443)
