name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-22.04, macOS-14]

    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      LISP: ${{ matrix.lisp }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up ${{ matrix.lisp }}
        uses: 40ants/setup-lisp@v2

      - name: Test syscall with ${{ matrix.lisp }} on ${{ runner.os }}
        uses: 40ants/run-tests@v2
        with:
          asdf-system: syscall
